### ISSUE TITLE
 java.net.SocketTimeoutException: failed to connect to settings.crashlytics.com/23.23.111.85 (port 443) after 10000ms

### ISSUE THREAD

**Issue by pbertsch** [crashlytics/crashlytics-services#118]
Hi,

Looking into my Logcat y see a lot of that errors and the IP seems not available.

Unknown error while loading Crashlytics settings. Crashes will be cached until settings can be retrieved.
                                           io.fabric.sdk.android.services.network.HttpRequest$HttpRequestException: java.net.SocketTimeoutException: failed to connect to settings.crashlytics.com/23.23.111.85 (port 443) after 10000ms
                                               at io.fabric.sdk.android.services.network.HttpRequest.code(HttpRequest.java:1392)
                                               at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.handleResponse(DefaultSettingsSpiCall.java:79)
                                               at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:66)
                                               at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:63)
                                               at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:47)
                                               at io.fabric.sdk.android.services.settings.Settings.loadSettingsData(Settings.java:139)
                                               at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:80)
                                               at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:26)
                                               at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:46)
                                               at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:11)
                                               at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:294)
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                               at java.lang.Thread.run(Thread.java:818)
                                            Caused by: java.net.SocketTimeoutException: failed to connect to settings.crashlytics.com/23.23.111.85 (port 443) after 10000ms
                                               at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
                                               at libcore.io.IoBridge.connect(IoBridge.java:122)
                                               at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                               at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                               at java.net.Socket.connect(Socket.java:884)
                                               at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                                               at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
                                               at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
                                               at com.android.okhttp.Connection.connect(Connection.java:143)
                                               at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                               at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                               at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
                                               at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                               at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                               at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
                                               at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                                               at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
                                               at io.fabric.sdk.android.services.network.HttpRequest.code(HttpRequest.java:1390)
                                               at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.handleResponse(DefaultSettingsSpiCall.java:79) 
                                               at io.fabric.sdk.android.services.settings.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:66) 
                                               at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:63) 
                                               at io.fabric.sdk.android.services.settings.DefaultSettingsController.loadSettingsData(DefaultSettingsController.java:47) 
                                               at io.fabric.sdk.android.services.settings.Settings.loadSettingsData(Settings.java:139) 
                                               at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:80) 
                                               at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:26) 
                                               at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:46) 
                                               at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:11) 
                                               at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:294) 
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                               at java.lang.Thread.run(Thread.java:818)

**Comment by mikebonnell** [comment]
@pbertsch If you're hitting issues with Crashlytics or Fabric, please raise them up at https://twittercommunity.com/c/fabric
